# Generated by Django 5.0.6 on 2024-07-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irisapp', '0004_alter_lifestyle_wedding_life_wed_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multi_Cam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multicam_image', models.ImageField(upload_to='multicam_image')),
            ],
        ),
    ]
