# Generated by Django 5.0.6 on 2024-07-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irisapp', '0005_multi_cam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_logo', models.ImageField(upload_to='client_logos')),
            ],
        ),
    ]
